### PR TITLE
Issue #124: Color cues

### LINKED ISSUE #124: Color cues
When a user attempts to add a blog that is already in the list, a blue bar appears on the top of the screen alerting the user that the blog already exists. Similarly, when trying to download blogs, if the blog no longer exists, a blue bar appears at the top of the screen alerting the user. Finally, certain other error messages (timeouts, for example) also appear in a blue bar at the top of the screen.

Would it be possible to distinguish the type of message by color? For example, when a blog no longer exists, rather than use a blue bar, use a red bar. In the case of a timeout, you could use a green or purple bar. This would help a user quickly recognize errors by type, especially when sorting through several messages.

### PR DESCRIPTION
**Pull request by arrowsmith001**
## Title

Suggestion that the error message bar should change colour depending on which error is being presented.

## Description

The user is unable to see, at a glance, which kind of error is being shown by the error message bar, particularly when closing several errors in succession. At present, all error messages have a blue background.

It was suggested that a red colour would be appropriate if a blog was missing, and a purple/green colour for timeout errors.

To address this, new colour resources should be added, and there should be a way for the error bar background to dynamically change in colour depending on the exception that is passed through.

## Issue Resolution

This Pull Request Fixes #124 Color cues

## Proposed Changes

- In BrushResource, changed ErrorBackground  to ErrorBackgroundBlue and added equivalents for Red, Purple and Green.
- Added LastErrorColor property to ShellViewModel which is databound to the error bar background, and provides a few variations in colour. At present, it returns Purple on a TimeOutException and Red on a WebException, and Blue otherwise.
- Modified the CloseButtonStyle to deal with an ugly mouse-over effect that's come about due to the colour change. I am really unfamiliar with WPF and XAML and this seems a bit hacky, so please amend if necessary. But at present, without this, the button shows a blue background regardless of the colour of the bar.

## Further Suggestions

- The resource dictionary call in ShellViewModel is not great. Someone should restructure this and expose the brush resources in a dedicated file somewhere.
- Error exceptions could be improved in general. It seems a lot of calls to ShowError pass "null" as an exception or otherwise lose useful information. If we better organised and categorized error exceptions, or even just passed a normalised string resource as the message within a new Exception, we could identify them at ShellViewModel level and have more bespoke colouring (depends how much colouring grading is really necessary). Personally, I think why not write some Exception classes for every type of error that may be shown to the user?

## New or Changed Features

 - Error message bar changes colour for several different error types

### CODE REVIEW

**Review by thomas694 — COMMENTED** [review]
Here's my two cents.

The resource dictionary call is acceptable. It could be extracted as member variable initialized once only in the constructor or at first time use.
As you probably meant, an even better way could be to return only an enum value, or int/string, from view model's "LastErrorColor" and use that value in the view with the help of a converter which converts it to the actual brush resource to be used. But it's questionable if that extra work is really worth it.

I just asked myself, if the resource names should contain a clue to the final color or be named more generic like the type of exception or categories in general, and the designer decides on the final color. But as it's all in our hands it's probably not much difference anyway.

Yes, you're right, for effectively categorizing the errors, it would be helpful, if at least some more exception classes would be used, or for the meantime the standard exception with well-known string tokens that are already categories or can be used for that. I just hovered the error bar, it seems more suitable to use new exception classes than tokens as the popup displays the exception's message as explanatory note. Another option would be to introduce a category parameter.

You can still improve it, if you want. Or we could write another issue for a beginner and guide him how to adapt the ShowError calls.

**Comment by arrowsmith001** [comment]
Latest changes and improvements:

I opted for LastErrorColor (now LastErrorColorString) to return a string that points to the resource and is handled by a converter as you suggested. I like this structure more, however searching for the resource dictionary on each call could still be avoided somehow. Also it may still be good to formally store the brush string tokens as resources somewhere.

I opted to keep the brush resources named by colour to give design flexibility in the future.

Lastly, I've added some exception classes which are no more than wrappers for the exceptions that were initially thrown. Now we can identify them better. I only decided to add the DiskFullException to our colour grading because that seems quite important, but the option to expand this is there in the future.

**Comment by thomas694** [comment]
Your code changes introduced two minor problems.

The custom exceptions lack serialization constructors (CA2229) and default constructors (CA1032). I think there's an error in our configuration and you didn't see these warnings, right?

The additional wrapping of the exceptions changes the error bar behavior.
Before:
```
Error 1: error getting clipboard content
  Tooltip: Internal error description
           <message text of the internal exception>
```
After:
```
Error 1: error getting clipboard content
  Tooltip: Internal error description
           Exception of type 'TumblThree.Applications.ClipboardContentException' was thrown.
```
This hides the original message and only shows the internal representation of the bar color. One quick fix could be to change it to `base(innerException?.Message, innerException)`.

**Review by thomas694 — CHANGES_REQUESTED** [review]
[see previous comment](https://github.com/TumblThreeApp/TumblThree/pull/133#issuecomment-808749005)

**Comment by arrowsmith001** [comment]
You're completely right to pick up that change due to the wrapping. I've changed that now.

As for the missing constructors, no, I did see the compiler warnings, but I ignored them. None of the use cases within the application went beyond the one constructor that I wrote so I saw no need to include the others. Also, by adding all of them it introduced all this hideous boilerplate code (see recently committed changes). I would like to have just written an ErrorException class that could handle all the constructors somehow then easily write these variations that extended this. Is this possible? If not, why bother? Genuine question. I'm not saying I know better.

**Comment by thomas694** [comment]
Of course, the code is all ours, so we could change it anytime we need in the future. But, in my opinion, our custom exceptions should follow best practices and .net standards.
I think you could use generics. Something like:
```csharp
    public class ErrorException<T> : Exception where T : Exception
    {
        public ErrorException() { }
        public ErrorException(string message) : base(message) { }
        public ErrorException(string message, Exception innerException) : base(message, innerException) { }
        public ErrorException(SerializationInfo info, StreamingContext context) : base(info, context) { }
    }
    public class MyErrorException : Exception { }
    public class MyErrorException2 : Exception { }
```
But then you would have to type more every time you want to use it:
```csharp
var ex = new ErrorException<MyErrorException>("message");
```
I'm fine with both. But personally, I would stick to letting it auto-implement four constructors once instead of writing longer lines multiple times, also for consistency with the .net framework or in other words how you are expecting to use exceptions normally.

**Comment by arrowsmith001** [comment]
That's an interesting idea with the generics but yeah this way seems more in line with the .net framework. Also not to mention it would be way more cumbersome finding out that generic type as opposed to just asking "is".

**Review by thomas694 — APPROVED** [review]
All good now. Thanks for taking care of this issue.

**Pull request merged**
