### PR TITLE
Fix tumblr %b argument in filename template

### PR DESCRIPTION
**Pull request by SpL1Ne**
## Title

Fix tumblr %b argument in filename download template

## Description

Tried to set %b in filename for tumblr downloader, but got empty string (i.e. %f-%b returns "tumblr_<uid>-.jpg" for post photo). So I looked into code and in process of fixing found that tumblr api doesn't return `Submitter` property in json response from blog that I tried to download neither from [tumblr demo blog](https://demo.tumblr.com/api/read/json). So instead of `Submitter` property of post data model I changed code to use `Tumblelog` property which contain `Name` property which store blog name. Also found that json response wasn't converted to `TumblrApiJson` class correctly. `TumbleLog` propery of `TumblrApiJson` class had empty fields despite the fact that the fields in the response were present. Same situation with `TumbleLog` propery of tubmlr `Post` class.

## Issue Resolution

No issue for this PR.

## Proposed Changes

 - using `Post.Tumblelog.name` property instead `Post.Submitter`.
 - added `[DataContract]` attribute to `TumbleLog` and `TumbleLog2` classes to fix `AbstractCrawler.ConvertJsonToClass<T>(json)` converter method.

## Additional info
Well, I didn't test fixes with many blog. Tested with first found blog `https://funnytwittertweets.tumblr.com/`, with [tumblr demo blog](https://demo.tumblr.com) and with the blog that I tried to download. Default settings, except filename template setting, which I set to `%b-%f`. Worked as it should.

Also, this is my first PR, sorry if something wrong with it.

### Non related info
[Wiki](https://github.com/TumblThreeApp/TumblThree/wiki/File-rename-functionality) page says that `%d  post date (yyyyMMddHHmmss)` but in reality `AbstractTumblrCrawler.BuildFileNameCore(*)` method is using `DateTime.Parse(date).ToString("yyyyMMdd")` output format.

### CODE REVIEW

**Comment by thomas694** [comment]
Thank you for your PR. 🙂
Today I don't have time, I'll take a look tomorrow.

**Comment by thomas694** [comment]
So, now the longer version...

No worries. We don't have super strict rules which must be followed to the last word.
You took the PR template as a guide and filled it out quite well. As you have already provided a solution and the issue is a small one, a created issue report isn't mandatory.

Obviously they changed/removed the `Submitter` field some time ago, maybe some other things too. In general, maybe you have recognized it in `TumblrSearchCrawler.cs`, I want to get rid off of these manually created json classes and replace them with `dynamic` objects loaded with the `Newtonsoft.Json` converter. That way we can use what we need and the rest of the json structure is kept and saved like it originally came in. I wanted to introduce it step by step each time a change in json structure requires a change in a crawler on our side.
That only as background information, you don't have to adapt that.

Your changes work except with the `Tumblr SVC` crawler, either chosen voluntarily in the blog settings or with the hidden blog crawler.
Can you please have a look at it?

> [Wiki](https://github.com/TumblThreeApp/TumblThree/wiki/File-rename-functionality) page says that `%d  post date (yyyyMMddHHmmss)` but in reality `AbstractTumblrCrawler.BuildFileNameCore(*)` method is using `DateTime.Parse(date).ToString("yyyyMMdd")` output format.

I think it's a "mistake" from earlier times when we hadn't the "time part" in a couple of cases. Maybe we should unify it soon.

Thanks for your work so far.

**Comment by SpL1Ne** [comment]
> Your changes work except with the Tumblr SVC crawler, either chosen voluntarily in the blog settings or with the hidden blog crawler.
> Can you please have a look at it?
Yeah, sure. Just tested at master branch, and v2.4.4 release, looks like this were there before with `%b` in filename template.
Will look at it.

> I want to get rid off of these manually created json classes and replace them with dynamic objects loaded with the Newtonsoft.Json converter. .. I wanted to introduce it step by step each time a change in json structure requires a change in a crawler on our side.
Well, you still have to change the code with the dynamic object, right? I mean, even if it was dynamic object, we would be still get error with `Submitter` and we had to change crawler on our side to update to `Tumblelog.name` but only but in fewer places, as far as I understand.

**Comment by thomas694** [comment]
> Well, you still have to change the code with the dynamic object, right? I mean, even if it was dynamic object, we would be still get error with `Submitter` and we had to change crawler on our side to update to `Tumblelog.name` but only but in fewer places, as far as I understand.

Yes, we have to adapt fewer places, only the few we are really interested in. I think in that case someone who uses the `%b` would have reported the error earlier, because it produces an error instead of just using the empty `Submitter` field.

**Comment by SpL1Ne** [comment]
Oh, right. However, don't know which will be better error or empty string.
Updated `Tumblr SVC`. Looks like they also removed `Publisher` property. Replaced with `Tumblelog` property of `Post` class.

**Review by thomas694 — APPROVED** [review]
It seems to work all now. Thanks for working on it.

**Comment by thomas694** [comment]
If you like to add or fix something in the future, you are welcome to do so.

**Comment by SpL1Ne** [comment]
Okay. Thank you for invite.

**Pull request merged**
