### PR TITLE
Prepare repository to be built by appveyor

### PR DESCRIPTION
**Pull request by gpriaulx**
Implement changes to support AppVeyor building TumblThree.

- AppVeyor configuration file (this now manages version)
- Pre-build script
- Post-build script
- Reset version in primary AssemblyInfo file to reduce confusion with local builds. 

- Remote service configuration

### CODE REVIEW

**Comment by gpriaulx** [comment]
This should resolve issue #12 

Verify artifacts are up to scratch here: https://ci.appveyor.com/project/gpriaulx/tumblthree/build/artifacts

AppVeyor will build on each commit to this repository, and publish artifacts to the same location. This enables anyone to get the latest dev build.  The process is pretty simple to customise. 

Note that the appveyor.yml file checked into the repo overrides settings in the AppVeyor UI.

**Comment by johanneszab** [comment]
Hi Gui!

Feel free to merge everything you like without asking me beforehand. If it's a larger modification, then we maybe should do it (same applies to be), but currently I don't want to hinder you developing TumblThree with my absence.

Same applies to releases (but I think they'll be automatically now ;))

**Comment by gpriaulx** [comment]
Hi mate,

No problem - I didn't want to step on your toes or meddle with your release process or preferences there etc. I'll probably still add you on any PRs I feel are significant for whatever reason, and if there is no movement in a week or two I'll just merge them in and deal with the aftermath myself. 

The builds will be automatic but the releases aren't at present. Not sure how to automate that - maybe the github api could be triggered from appveyor to do so if desired. I would imagine all that is necessary now to do a formal release is to go to appveyor, download the artifacts and just upload to github. At the very least it means any repo admin can do it, and the builds are done consistently. 

I'll check the current version now and make sure it works!

**Comment by johanneszab** [comment]
Okay! We need to change urls (e.g. for the CheckUpdateService (or how it was called)) to it's new github home. But I can quickly do this..

**Comment by gpriaulx** [comment]
Oh right - good call. Does that mean we need an immediate release for the update service to find something?

**Pull request merged**
