### PR TITLE
[SOLVED] Issue #101 "Can not download a specific tumblr anymore"

### PR DESCRIPTION
**Pull request by arrowsmith001**
## Title

Issue #101 "Can not download a specific tumblr anymore"

## Description

The contents of a particular Tumblr blog (https://protobacillus.tumblr.com/) could not be retrieved by the crawler.

## Issue Resolution

I believe the problem was due to the code not accounting for the HTTP response status code 301 ("Moved").

## Proposed Changes

AbstractCrawler.RequestDataAsync checks for HttpStatusCode.Moved until it returns a response, in addition to HttpStatusCode.Found. To assist the above, WebRequestFactory.ReadRequestToEnd2Async sets the "Location" header in the case of HttpStatusCode.Moved.

## New or Changed Features

The contents of blogs that have been moved to a new URL can now be retrieved.

### CODE REVIEW

**Review by thomas694 — CHANGES_REQUESTED** [review]
That looks good. This blog can be crawled and files be downloaded.
But it introduces something which should be addressed. It makes a second round trip necessary for every new request.
Can you find a way to update the blog's old url to use the new url from then on?

**Comment by arrowsmith001** [comment]
The only sure solution I can think of is to cache the redirect URL in a Dictionary somewhere with the lookup key being the original URL. This might be a bit overkill because I would save similar API calls separately with their corresponding redirect. I was thinking that after GetApiUrl is called by GetApiPageAsync, we could have:

url = redirectService.GetRedirectedUrl(url); // where redirectService : IRedirectService

However I'm not sure how to best architect this in the current context.

Note: Even though, here, the redirect is just the original + "#_=_", I don't have evidence that suggests this pattern will hold for all future redirects. Even if that is the case, we would need to at least set a flag somewhere that makes TumblrBlogCrawler use the "redirected version" in all future API URL fetches for that blog.

Please advise.

**Comment by arrowsmith001** [comment]
Ok I'm not sure if this is the proper way to do it, but I committed some changes to the same branch and the PR seems to have updated. It is just a concept though using static properties of a RedirectService class because I am unsure of how to integrate it into the current architecture - this is just for demonstration of the idea.

I would like to know also how to save the cache data locally to use when the application is restarted.

**Comment by thomas694** [comment]
Yes, further commits to the branch are ok, it automatically updates the PR.

I think you don't need to introduce a redirect service that keeps track of the old and new urls with a dictionary. A 301 (moved permanently) indicates that future requests shall be done with the new url. In case of Tumblr, normally only blogs (and not e.g. searches) are redirected because the blog owners want to use their private domain name. So I think you could do it in another way.

If you keep your change in WebRequestFactory.ReadRequestToEnd2Async, I think it already returns all information you need outside.
When returning to RequestDataAsync you could check if it's a permanent move (Moved/301) and the url authority part (e.g. protobacillus.tumblr.com) changed, but not when changing to Tumblr domain (e.g. login / privacy consent redirects or similar). In the former case it's ok to change the blog's url to the new one (e.g. www.protobacillus.com). The blog object is accessible from inside AbstractCrawler, so you can just change its url property. Of course you could write this code inside a RedirectService class, but as it's probably only a function, this can just be a function inside AbstractCrawler.

That probably would be what I would try.

**Comment by arrowsmith001** [comment]
I think the latest commit is close to what you're looking for, and it seems to work.

**Review by thomas694 — APPROVED** [review]
It looks good now.

**Pull request merged**
